export const strings = {
  app: {
    title: "Pool Simulator",
  },
  home: {
    goToTable: "Go to the Table",
    scenarios: "Scenarios",
    debugScenarios: "Debug Scenarios",
  },
  screens: {
    home: "Home",
    table: "Table",
    freePlay: "Free Play",
    scenarios: "Scenarios",
    debugScenarios: "Debug Scenarios",
  },
  table: {
    shoot: "Shoot",
    reset: "Reset",
    aimLeft: "◀",
    aimRight: "▶",
    aimLeftFine: "◁",
    aimRightFine: "▷",
    placeCue: "Tap the table to place the white ball",
    youWin: "You win!",
    youLose: "You lose",
    foul: (reason: string) => `Foul: ${reason}`,
    assignedSolids: "You are Solids (1-7)",
    assignedStripes: "You are Stripes (9-15)",
    potTheEight: "Pot the 8",
  },
  history: {
    title: "Shot History",
    noShots: "No shots taken yet",
    replayAll: "Replay",
    latest: "Latest",
    shot: (n: number) => `Shot ${n}`,
    goToShot: (n: number) => `Go to Shot ${n}`,
    goToLatest: "Go to Latest",
    controls: "Controls",
    history: "History",
    back: "Back",
  },
  scenarios: {
    free_play: { name: "Free Play", description: "Full rack — 15 balls" },
    random: { name: "Random", description: "Randomly placed balls" },
    rolling_direct: { name: "Rolling Direct", description: "Natural roll into object ball" },
    half_ball_rolling: { name: "Rolling ½ Ball", description: "Rolling cut shot" },
    stop_shot: { name: "Stop Shot", description: "Backspin — cue stops dead" },
    half_ball_stun: { name: "Stun ½ Ball", description: "Stun cut along tangent line" },
    max_draw: { name: "Max Draw", description: "Full backspin — cue draws back" },
    max_follow: { name: "Max Follow", description: "Full topspin — cue follows through" },
    lag_shot: { name: "Lag Shot", description: "Gentle roll to far rail and back" },
    baulk_to_rail: { name: "Baulk to Rail", description: "Calibration — just reaches far rail" },
    pot_corner_tr: { name: "Pot Corner TR", description: "Straight pot into top-right corner" },
    pot_corner_tl: { name: "Pot Corner TL", description: "Straight pot into top-left corner" },
    pot_corner_br: { name: "Pot Corner BR", description: "Straight pot into bottom-right corner" },
    pot_corner_bl: { name: "Pot Corner BL", description: "Straight pot into bottom-left corner" },
    pot_side: { name: "Pot Side", description: "Straight shot into side pocket" },
    pot_side_higher: { name: "Pot Side Higher", description: "Straight shot into side pocket from higher position" },
    pot_side_right: { name: "Pot Side Right", description: "Straight shot into right side pocket" },
    curve_into_pocket: { name: "Curve Into Pocket", description: "Follow-cut curves the cue ball into a corner it would otherwise slide past" },
    corner_jaw_skim: { name: "Corner Jaw Skim", description: "Shallow-angle shot skims a pocket mouth and bounces off the jaw cushion instead of escaping the table" },
    straight_down_x15th: { name: "Straight Down (x = w/15)", description: "Ball shot straight down the table near a corner, at x = table width / 15 — checks the rail-vs-jaw boundary" },
    draw_creep: { name: "Draw Creep", description: "Cue ball stops dead on a full hit but draws back afterward from leftover backspin" },
    throw_off_line: { name: "Throw Off Line", description: "Cue-ball sidespin (english) throws the cut ball off the true tangent line" },
    squirt_miss: { name: "Squirt Miss", description: "Uncompensated sidespin squirts the cue ball off a dead-straight aim, missing the object ball entirely" },
    cushion_english: { name: "Cushion English", description: "Sidespin changes the cue ball's rebound angle off a single rail bounce, landing far from a spinless bank" },
    two_ball: { name: "Two Ball", description: "Cue ball and object ball — aim freely" },
    endgame: { name: "Endgame", description: "8-ball, one solid, one stripe — finish the frame" },
    mid_game_spread: { name: "Tor Lowry Example", description: "Mid-game position — balls spread across the table" },
  },
} as const;

export type ScenarioId = keyof typeof strings.scenarios;
